language: python
cache: pip

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-djangomaster

sudo: false

services:
  - redis-server

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djangomaster

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coverage combine
  - coveralls